/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TutorialStandaloneSetup extends TutorialStandaloneSetupGenerated {

	public static void doSetup() {
		new TutorialStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
