/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TutorialUiModule extends AbstractTutorialUiModule {

	public TutorialUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
